### ISSUE TITLE
Update arXiv icon

### ISSUE THREAD

**Issue by sebastiendesignolle** [jpswalsh/academicons#201] opened 2023-05-07 21:20 UTC
## Organisation

- Name: arXiv
- Website: https://arxiv.org/

## Scope

The icon currently available is no longer up to date, see https://info.arxiv.org/brand/logos.html, where a monochrome version is available.

## Technical checks

Confirm each of the following by checking the box. If the last two points cannot be confirmed, it is highly unlikely that the logo will be added to Academicons.

- [ x ] The organisation is using a logo/icon of appropriate dimensions (roughly square).
- [ x ] The icon can be reduced to monochrome.
- [ x ] A vector file (e.g. SVG, EPS, AI) or a PDF with the vector file embedded can be provided or linked to.

**Comment by nfrerebeau** [comment] 2023-05-31 17:51
Duplicate of #174.

**Closed by nfrerebeau** 2023-05-31 17:51 UTC
Labels: enhancement
