### ISSUE TITLE
Icon Request: LinkedIn

### ISSUE THREAD

**Issue by yccui** [jpswalsh/academicons#187] opened 2022-09-17 04:08 UTC
## Organisation

- Name:
- Website:

## Scope

Briefly explain why you think this organisation should be added to Academicons.

## Technical checks

Confirm each of the following by checking the box. If the last two points cannot be confirmed, it is highly unlikely that the logo will be added to Academicons.

- [ ] The organisation is using a logo/icon of appropriate dimensions (roughly square).
- [ ] The icon can be reduced to monochrome.
- [ ] A vector file (e.g. SVG, EPS, AI) or a PDF with the vector file embedded can be provided or linked to.

**Comment by nfrerebeau** [comment] 2022-10-14 13:16
Duplicate of #167.

**Closed by nfrerebeau** 2022-10-14 13:16 UTC
